# Generated by Django 3.1 on 2020-08-29 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('minutes', models.IntegerField()),
                ('n_steps', models.IntegerField()),
                ('steps', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=500)),
                ('n_ingredients', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbohydrates', models.DecimalField(decimal_places=1, max_digits=5)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
    ]
